name: Feature request
description: Propose a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve agentpack!

        Tips:
        - Describe the user workflow and expected outcome.
        - If this affects `--json`, include the intended contract changes.

  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
      description: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should agentpack do? Include CLI examples if possible.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other approaches did you consider?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, screenshots, related issues, etc.
    validations:
      required: false
